version: '{build}'
skip_tags: true

environment:
  ANDROID_HOME: C:\android-sdk 
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

configuration: Release

install:
  - mkdir %ANDROID_HOME%
  - curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/tools_r25.2.5-windows.zip
  - 7z x -o%ANDROID_HOME% tools_r25.2.5-windows.zip

  - nuget install Embeddinator-4000

build: 
    project: libWindBot.sln
    parallel: true

test: off

artifacts:
  - path: output/*
    name: libWindBot

deploy:
  release: latest
  description: 'Automatic build commit $(APPVEYOR_REPO_COMMIT) $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  force_update: true
  auth_token:
    secure: EQ9miMjfX/QAoBvgc6D+JLmHatLyxOEKZ/uo68QijxWW5Gp4MzB/pOH9+u2GlDVO
  on:
    branch: master
