version: '{build}'
skip_tags: true

environment:
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

configuration: Release

install:
  - curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://dl.google.com/android/repository/android-ndk-r10e-windows-x86_64.zip
  - 7z x -y android-ndk-r10e-windows-x86_64.zip
  - mv -f android-ndk-r10e C:\ProgramData\Microsoft\AndroidNDK

  - echo y | "%ANDROID_HOME%\tools\android" update sdk --no-ui --all --filter "platform-tools"
  - echo y | "%ANDROID_HOME%\tools\android" update sdk --no-ui --all --filter "tools"
  - echo y | "%ANDROID_HOME%\tools\android" update sdk --no-ui --all --filter "android-25"

  - nuget install Embeddinator-4000

build: 
    project: libWindBot.sln
    parallel: true

test: off

artifacts:
  - path: output/*
    name: libWindBot

deploy:
  release: latest
  description: 'Automatic build commit $(APPVEYOR_REPO_COMMIT) $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  force_update: true
  auth_token:
    secure: EQ9miMjfX/QAoBvgc6D+JLmHatLyxOEKZ/uo68QijxWW5Gp4MzB/pOH9+u2GlDVO
  on:
    branch: master
