version: '{build}'

configuration: Release

install:
 - # nuget install Xamarin
 - nuget install Embeddinator-4000

build: 
    project: libWindBot.sln
    parallel: true

test: off

artifacts:
  - path: bin/Release/*
    name: libWindBot

deploy:
  release: latest
  description: 'Automatic build commit $(APPVEYOR_REPO_COMMIT) $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  force_update: true
  auth_token:
    secure: EQ9miMjfX/QAoBvgc6D+JLmHatLyxOEKZ/uo68QijxWW5Gp4MzB/pOH9+u2GlDVO
  on:
    branch: master
